version: '3'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    networks:
      - default
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./create.sql:/docker-entrypoint-initdb.d/create_tables.sql

  app:
    build: .
    command: yarn dev
    ports:
      - 3333:3333
    networks:
      - default
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      - DATABASE_URL=postgres://postgres:postgres@host.docker.internal:5432/ngcash
      - JWT_SECRET_KEY=nuifHWOUJFAWUIFH28u09dwkjndiuahd8
      - JWT_EXPIRATION_TIME=1d
    volumes:
      - .:/usr/app
    depends_on:
      - db